test new cointainer

diff --git a/inst/Docker/Generation/Dockerfile b/inst/Docker/Generation/Dockerfile
--- a/inst/Docker/Generation/Dockerfile
+++ b/inst/Docker/Generation/Dockerfile
@@ -1,124 +1,130 @@
-#================================================================================
-# Stage 1: build all the GreatSPN modules and their dependencies
-#================================================================================
-# Set up the base environment
+# syntax=docker/dockerfile:1.4
+
+###############################################################################
+# Stage 1 ─ builder: compila GreatSPN & dipendenze
+###############################################################################
 FROM debian:bullseye AS builder
 
-RUN apt-get update && apt-get install -y sudo adduser apt-utils wget
+# -------- shell + pipefail + apt retry --------------------------------------
+SHELL ["/bin/bash", "-o", "pipefail", "-c"]
+ARG DEBIAN_FRONTEND=noninteractive
+RUN echo 'Acquire::Retries "5";\n\
+Acquire::http::Timeout "25";\n\
+Acquire::https::Timeout "25";' > /etc/apt/apt.conf.d/80-retries
 
-# Create the 'docker' user
-RUN /usr/sbin/adduser --disabled-password --gecos '' docker
+# -------- pacchetti di sistema ----------------------------------------------
+RUN apt-get update && \
+    for i in {1..3}; do \
+      echo "APT install attempt $i (builder)"; \
+      apt-get install -y --no-install-recommends \
+        sudo adduser apt-utils wget \
+        gcc g++ libgmp-dev libgmpxx4ldbl libboost-all-dev \
+        flexc++ ant libglib2.0-dev patch python3 libglpk-dev liblpsolve55-dev \
+        autoconf automake libtool zip flex byacc time graphviz libsuitesparse-dev \
+        libmotif-dev make libxml++2.6-dev libglibmm-2.4-dev texlive-font-utils \
+        openjdk-17-jdk cmake git ghostscript libfl-dev && break; \
+      echo "APT failed – retrying…"; sleep 20; apt-get update; \
+    done && \
+    rm -rf /var/lib/apt/lists/*
 
-# Add the 'docker' user to the 'sudo' group
-RUN usermod -aG sudo docker
-
-# Allow 'sudo' without password for users in the 'sudo' group
-RUN echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers
-
-# Switch to the 'docker' user
+# -------- utente non-root ----------------------------------------------------
+RUN /usr/sbin/adduser --disabled-password --gecos '' docker && \
+    usermod -aG sudo docker && \
+    echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers
 USER docker
-
-# Set the working directory
 WORKDIR /home/docker
-
-RUN sudo apt-get install -y gcc g++ libgmp-dev libgmpxx4ldbl libboost-all-dev \
-     flexc++ ant libglib2.0-dev patch python3 libglpk-dev liblpsolve55-dev \
-     autoconf automake libtool zip flex byacc time graphviz libsuitesparse-dev \
-     libmotif-dev make libxml++2.6-dev libglibmm-2.4-dev texlive-font-utils \
-     openjdk-17-jdk cmake git ghostscript libfl-dev wget
 ENV MAKE_ARGS=-j4
 
-# Install Meddly
-RUN git clone https://github.com/asminer/meddly.git meddly && \
-    cd meddly && \
-    git checkout v0.17.0 && \
-    ./autogen.sh && \
-    ./configure --prefix=/usr/local && \
-    make ${MAKE_ARGS} && \
-    sudo make install
+# -------- Meddly ------------------------------------------------------------
+RUN git clone https://github.com/asminer/meddly.git && \
+    cd meddly && git checkout v0.17.0 && \
+    ./autogen.sh && ./configure --prefix=/usr/local && \
+    make ${MAKE_ARGS} && sudo make install
 
-# Add Meddly to environment paths
-ENV C_INCLUDE_PATH="/usr/local/include:$C_INCLUDE_PATH"
-ENV LIBRARY_PATH="/usr/local/lib:$LIBRARY_PATH"
-ENV LD_LIBRARY_PATH="/usr/local/lib:$LD_LIBRARY_PATH"
-
-# Install SPOT for now no
-#RUN wget http://www.lrde.epita.fr/dload/spot/spot-2.9.6.tar.gz && \
-#    tar xzf spot-2.9.6.tar.gz && \
-#    cd spot-2.9.6 && \
-#    ./configure --disable-python --disable-debug && \
-#    make ${MAKE_ARGS} && \
-#    sudo make install
-
-# Install OGDF
-RUN for i in 1 2 3; do \
-    git clone https://github.com/ogdf/ogdf.git && break || sleep 5; \
+# -------- OGDF --------------------------------------------------------------
+RUN for n in {1..3}; do \
+      git clone https://github.com/ogdf/ogdf.git && break || sleep 10; \
     done && \
-    cd ogdf && \
-    mkdir build && cd build && \
-    cmake .. && \
-    make ${MAKE_ARGS} && \
-    sudo make install
+    cd ogdf && mkdir build && cd build && cmake .. && \
+    make ${MAKE_ARGS} && sudo make install
 
-# Install lp_solve
-RUN wget -O lp_solve_5.5.2.11_source.tar.gz "https://downloads.sourceforge.net/project/lpsolve/lpsolve/5.5.2.11/lp_solve_5.5.2.11_source.tar.gz?viasf=1" && \
+# -------- lp_solve ----------------------------------------------------------
+RUN wget -O lp_solve.tar.gz \
+      https://downloads.sourceforge.net/project/lpsolve/lpsolve/5.5.2.11/lp_solve_5.5.2.11_source.tar.gz && \
     wget https://raw.githubusercontent.com/LorenzoChiabrando/SOURCES/master/contrib/build_lpsolve.sh && \
-    tar xzf lp_solve_5.5.2.11_source.tar.gz && \
-    chmod +x ./build_lpsolve.sh && \
-    /bin/bash ./build_lpsolve.sh
+    tar xzf lp_solve.tar.gz && \
+    chmod +x build_lpsolve.sh && ./build_lpsolve.sh
 
-
-# Install GreatSPN
-# Install GreatSPN
-RUN mkdir ~/GreatSPN && \
-    cd ~/GreatSPN && \
-    for i in {1..5}; do git clone https://github.com/LorenzoChiabrando/SOURCES.git SOURCES && break || sleep 5; done && \
-    cd ~/GreatSPN/SOURCES && \
+# -------- GreatSPN ----------------------------------------------------------
+RUN mkdir -p ~/GreatSPN && cd ~/GreatSPN && \
+    for n in {1..5}; do \
+      git clone https://github.com/LorenzoChiabrando/SOURCES.git SOURCES && break || sleep 10; \
+    done && \
+    cd SOURCES && \
     make ${MAKE_ARGS} -k derived_objects && \
-    make ${MAKE_ARGS} && \
-    sudo make install
+    make ${MAKE_ARGS} && sudo make install
 
-
-#================================================================================
-# Stage 2: prepare the deployment image with the non-devel packages
-#================================================================================
+###############################################################################
+# Stage 2 ─ deploy_base: runtime minimale
+###############################################################################
 FROM r-base:4.2.2 AS deploy_base
+SHELL ["/bin/bash", "-o", "pipefail", "-c"]
+ARG DEBIAN_FRONTEND=noninteractive
+RUN echo 'Acquire::Retries "5";\n\
+Acquire::http::Timeout "25";\n\
+Acquire::https::Timeout "25";' > /etc/apt/apt.conf.d/80-retries
 
-RUN apt-get update ; apt-get install -y sudo adduser apt-utils
-# RUN /usr/sbin/adduser --disabled-password --gecos '' docker
-RUN /usr/sbin/adduser docker sudo
-RUN echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers
+RUN apt-get update && \
+    for i in {1..3}; do \
+      echo "APT install attempt $i (deploy_base)"; \
+      apt-get install -y --no-install-recommends \
+        sudo adduser apt-utils \
+        gcc g++ libgmp10 libgmpxx4ldbl libglpk40 \
+        flexc++ python3 flex time graphviz bison libglpk-dev \
+        make openjdk-17-jre git ghostscript && break; \
+      echo "APT failed – retrying…"; sleep 20; apt-get update; \
+    done && \
+    rm -rf /var/lib/apt/lists/*
+
+RUN /usr/sbin/adduser docker sudo && \
+    echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers
 USER docker
 WORKDIR /home/docker
 
-RUN sudo apt-get install -y gcc g++ libgmp10 libgmpxx4ldbl \
-     flexc++ python3 libglpk40 \
-     flex time graphviz bison libglpk-dev \
-     make openjdk-17-jre git ghostscript
-
-#================================================================================
-# Stage 3: Update the GreatSPN framework by pulling/remaking the latest changes
-#================================================================================
+###############################################################################
+# Stage 3 ─ updater (opzionale, se vuoi il pull recente)
+###############################################################################
 FROM builder AS updater
-
-ARG update_version
+ARG UPDATE_VERSION
 RUN cd ~/GreatSPN/SOURCES && \
     git pull && \
     make ${MAKE_ARGS} -k derived_objects && \
-    make ${MAKE_ARGS} && \
-    sudo make install
+    make ${MAKE_ARGS} && sudo make install
 
-#================================================================================
-# Stage 4: Copy the compiled binaries into the deployment image
-#================================================================================
+###############################################################################
+# Stage 4 ─ immagine finale di runtime
+###############################################################################
 FROM deploy_base
+SHELL ["/bin/bash", "-o", "pipefail", "-c"]
 
-# Copia i binari compilati
-COPY --from=updater /usr/local/GreatSPN /usr/local/GreatSPN
-COPY --from=updater /usr/local/lib /usr/local/lib
-RUN sudo rm -rf /usr/local/lib/*.a /usr/local/lib/*.la
+# --- Copia binari compilati (owner già 1000:1000) ----------------------------
+COPY --from=updater --chown=1000:1000 /usr/local/GreatSPN /usr/local/GreatSPN
+COPY --from=updater --chown=1000:1000 /usr/local/lib       /usr/local/lib
 
-# Aggiungi i percorsi delle librerie e dei binari
-RUN echo '/usr/local/lib' | sudo tee /etc/ld.so.conf.d/greatspn.conf && sudo ldconfig
-ENV PATH="$PATH:/usr/local/GreatSPN/scripts"
+# --- Permessi & workdir ------------------------------------------------------
+USER root
+RUN mkdir -p /home && chown -R 1000:1000 /home
+
+# 🔧 rimuovi i .a/.la da root
+RUN find /usr/local/lib -name '*.a' -o -name '*.la' -delete
+
+WORKDIR /home
+USER 1000:1000
+
+
+# --- Linker & PATH -----------------------------------------------------------
+USER root
+RUN echo '/usr/local/lib' > /etc/ld.so.conf.d/greatspn.conf && ldconfig
+USER 1000:1000
+ENV PATH="/usr/local/GreatSPN/scripts:${PATH}"
 
